version: "3"
services:
  web:
    image: docker.lappsgrid.org/lappsgrid/stanford:gdd
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 3G
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:
